In [6]:
import pandas as pd
from io import StringIO

data = '''user_id,age,avg_weekly_visits,last_purchase_days_ago,segment,region,subject_line_version,email_clicked,feedback_text
1,23,3,40,Occasional,North,A,0,"Looks okay but I am not very interested right now."
2,35,8,5,Loyal,South,B,1,"Great offer, I was waiting for this discount!"
3,29,2,120,ChurnRisk,East,A,0,"Too many emails, I might unsubscribe soon."
4,42,6,20,Regular,West,B,1,"Nice reminder, I decided to add a few items to cart."
5,31,1,200,ChurnRisk,North,A,0,"Not relevant to me."
6,27,5,10,Occasional,South,B,1,"Helpful email, I finally tried the premium plan."
7,38,4,60,Regular,East,A,0,"I saw it but did not feel the need to buy."
8,45,9,3,Loyal,West,B,1,"Loved the bundle offer, very attractive."
9,26,2,150,Occasional,North,A,0,"Offer is fine but my budget is tight."
10,33,7,15,Regular,South,B,1,"Good deal, I clicked and checked new arrivals."'''

df = pd.read_csv(StringIO(data))

In [7]:
df

,user_id,age,avg_weekly_visits,last_purchase_days_ago,segment,region,subject_line_version,email_clicked,feedback_text
0,1,23,3,40,Occasional,North,A,0,Looks okay but I am not very interested right ...
1,2,35,8,5,Loyal,South,B,1,"Great offer, I was waiting for this discount!"
2,3,29,2,120,ChurnRisk,East,A,0,"Too many emails, I might unsubscribe soon."
3,4,42,6,20,Regular,West,B,1,"Nice reminder, I decided to add a few items to..."
4,5,31,1,200,ChurnRisk,North,A,0,Not relevant to me.
5,6,27,5,10,Occasional,South,B,1,"Helpful email, I finally tried the premium plan."
6,7,38,4,60,Regular,East,A,0,I saw it but did not feel the need to buy.
7,8,45,9,3,Loyal,West,B,1,"Loved the bundle offer, very attractive."
8,9,26,2,150,Occasional,North,A,0,Offer is fine but my budget is tight.
9,10,33,7,15,Regular,South,B,1,"Good deal, I clicked and checked new arrivals."

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 10 non-null     int64
 1   age                     10 non-null     int64
 2   avg_weekly_visits       10 non-null     int64
 3   last_purchase_days_ago  10 non-null     int64
 4   segment                 10 non-null     object
 5   region                  10 non-null     object
 6   subject_line_version    10 non-null     object
 7   email_clicked           10 non-null     int64
 8   feedback_text           10 non-null     object
dtypes: int64(5), object(4)
memory usage: 852.0+ bytes

In [11]:
df.isnull().sum()

user_id                   0
age                       0
avg_weekly_visits         0
last_purchase_days_ago    0
segment                   0
region                    0
subject_line_version      0
email_clicked             0
feedback_text             0
dtype: int64

In [12]:
df.describe()

,user_id,age,avg_weekly_visits,last_purchase_days_ago,email_clicked
count,10.00000,10.00000,10.000000,10.000000,10.000000
mean,5.50000,32.90000,4.700000,62.300000,0.500000
std,3.02765,7.14065,2.750757,69.957209,0.527046
min,1.00000,23.00000,1.000000,3.000000,0.000000
25%,3.25000,27.50000,2.250000,11.250000,0.000000
50%,5.50000,32.00000,4.500000,30.000000,0.500000
75%,7.75000,37.25000,6.750000,105.000000,1.000000
max,10.00000,45.00000,9.000000,200.000000,1.000000

In [16]:
y = df['email_clicked']
X = df.drop(columns = ['email_clicked'])

In [17]:
X

,user_id,age,avg_weekly_visits,last_purchase_days_ago,segment,region,subject_line_version,feedback_text
0,1,23,3,40,Occasional,North,A,Looks okay but I am not very interested right ...
1,2,35,8,5,Loyal,South,B,"Great offer, I was waiting for this discount!"
2,3,29,2,120,ChurnRisk,East,A,"Too many emails, I might unsubscribe soon."
3,4,42,6,20,Regular,West,B,"Nice reminder, I decided to add a few items to..."
4,5,31,1,200,ChurnRisk,North,A,Not relevant to me.
5,6,27,5,10,Occasional,South,B,"Helpful email, I finally tried the premium plan."
6,7,38,4,60,Regular,East,A,I saw it but did not feel the need to buy.
7,8,45,9,3,Loyal,West,B,"Loved the bundle offer, very attractive."
8,9,26,2,150,Occasional,North,A,Offer is fine but my budget is tight.
9,10,33,7,15,Regular,South,B,"Good deal, I clicked and checked new arrivals."

In [18]:
y

0    0
1    1
2    0
3    1
4    0
5    1
6    0
7    1
8    0
9    1
Name: email_clicked, dtype: int64

In [22]:
num_features = ['user_id','age','avg_weekly_visits','last_purchase_days_ago']
cat_features = ['segment','region','subject_line_version']

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

preprocessor =  ColumnTransformer(transformers = [("Scaling_num_features", StandardScaler(), num_features),
        ("OHE_cat_features", OneHotEncoder(handle_unknown ="ignore"),cat_features)])

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state = 42, shuffle = True)


steps = [('pre-processing',preprocessor),
         ('RF_classifier',RandomForestClassifier())]

pipe1 = Pipeline(steps = steps)

In [23]:
pipe1.fit(X_train,y_train)

Pipeline(steps=[('pre-processing',
                 ColumnTransformer(transformers=[('Scaling_num_features',
                                                  StandardScaler(),
                                                  ['user_id', 'age',
                                                   'avg_weekly_visits',
                                                   'last_purchase_days_ago']),
                                                 ('OHE_cat_features',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['segment', 'region',
                                                   'subject_line_version'])])),
                ('RF_classifier', RandomForestClassifier())])

In [30]:
y_pred = pipe1.predict(X_test)

In [26]:
y_test

8    0
1    1
5    1
Name: email_clicked, dtype: int64

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_report = accuracy_score(y_test, y_pred)
print(accuracy_report)

classification_rf = classification_report(y_test, y_pred, output_dict = True)
print(classification_rf)

confusion_mat_rf = confusion_matrix(y_test,y_pred)
print(confusion_mat_rf)

1.0
{'0': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 1.0}, '1': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 2.0}, 'accuracy': 1.0, 'macro avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}, 'weighted avg': {'precision': 1.0, 'recall': 1.0, 'f1-score': 1.0, 'support': 3.0}}
[[1 0]
 [0 2]]

In [46]:
from transformers import pipeline

nlp = pipeline("sentiment-analysis")

Device set to use cpu

In [47]:
sentiment_result = df['feedback_text'].apply(nlp)

In [48]:
print(sentiment_result)

0    [{'label': 'NEGATIVE', 'score': 0.998366057872...
1    [{'label': 'POSITIVE', 'score': 0.985491931438...
2    [{'label': 'NEGATIVE', 'score': 0.997910559177...
3    [{'label': 'POSITIVE', 'score': 0.998981654644...
4    [{'label': 'NEGATIVE', 'score': 0.999782383441...
5    [{'label': 'POSITIVE', 'score': 0.582445085048...
6    [{'label': 'NEGATIVE', 'score': 0.972954571247...
7    [{'label': 'POSITIVE', 'score': 0.999877691268...
8    [{'label': 'NEGATIVE', 'score': 0.709110558032...
9    [{'label': 'POSITIVE', 'score': 0.995584845542...
Name: feedback_text, dtype: object

In [49]:
df['Feedback_sentiment_label'] = sentiment_result.apply(lambda x: x[0]['label'])
df['Feedback_sentiment_score'] = sentiment_result.apply(lambda x: x[0]['score'])

In [53]:
grouped = df.groupby('Feedback_sentiment_label').agg({'email_clicked' : 'mean','feedback_text' : 'count'
}).rename(columns = {'email_clicked': 'avg_email_clicked', 'feedback_text': 'count_feedback' })

print(grouped)

                          avg_email_clicked  count_feedback
Feedback_sentiment_label
NEGATIVE                                0.0               5
POSITIVE                                1.0               5

⚠️ Important Note
This is a small dataset (only 10 samples), so the correlation looks absolute but may not generalize.

In larger, real-world datasets, you’d expect more variation,some positive feedback without clicks, some negative feedback with clicks.
But, from the above output I conclude my interpretation.

🔍 Interpretation
Negative feedback: 5 users, none clicked the email (0% click rate).

Positive feedback: 5 users, all clicked the email (100% click rate).

So in this tiny sample, there’s a perfect correlation: when feedback sentiment is positive, users always click; when feedback sentiment is negative, they never click.